<?php

/**
 * BaseMailingList2Email
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $mailing_list_id
 * @property integer $email_id
 * @property string $name
 * @property string $phone
 * @property integer $status
 * @property Doctrine_Collection $MailingList
 * @property Doctrine_Collection $Email
 * 
 * @method integer             getMailingListId()   Returns the current record's "mailing_list_id" value
 * @method integer             getEmailId()         Returns the current record's "email_id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method string              getPhone()           Returns the current record's "phone" value
 * @method integer             getStatus()          Returns the current record's "status" value
 * @method Doctrine_Collection getMailingList()     Returns the current record's "MailingList" collection
 * @method Doctrine_Collection getEmail()           Returns the current record's "Email" collection
 * @method MailingList2Email   setMailingListId()   Sets the current record's "mailing_list_id" value
 * @method MailingList2Email   setEmailId()         Sets the current record's "email_id" value
 * @method MailingList2Email   setName()            Sets the current record's "name" value
 * @method MailingList2Email   setPhone()           Sets the current record's "phone" value
 * @method MailingList2Email   setStatus()          Sets the current record's "status" value
 * @method MailingList2Email   setMailingList()     Sets the current record's "MailingList" collection
 * @method MailingList2Email   setEmail()           Sets the current record's "Email" collection
 * 
 * @package    SystemCore
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMailingList2Email extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mailing_list2_email');
        $this->hasColumn('mailing_list_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('email_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MailingList', array(
             'local' => 'mailing_list_id',
             'foreign' => 'id'));

        $this->hasMany('Email', array(
             'local' => 'email_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}