<?php

/**
 * BaseMailing
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $title
 * @property text $html
 * @property text $public
 * @property integer $status
 * @property User $User
 * 
 * @method integer getUserId()  Returns the current record's "user_id" value
 * @method string  getTitle()   Returns the current record's "title" value
 * @method text    getHtml()    Returns the current record's "html" value
 * @method text    getPublic()  Returns the current record's "public" value
 * @method integer getStatus()  Returns the current record's "status" value
 * @method User    getUser()    Returns the current record's "User" value
 * @method Mailing setUserId()  Sets the current record's "user_id" value
 * @method Mailing setTitle()   Sets the current record's "title" value
 * @method Mailing setHtml()    Sets the current record's "html" value
 * @method Mailing setPublic()  Sets the current record's "public" value
 * @method Mailing setStatus()  Sets the current record's "status" value
 * @method Mailing setUser()    Sets the current record's "User" value
 * 
 * @package    SystemCore
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMailing extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mailing');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('html', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('public', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}