<?php

/**
 * BaseMailingList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $name
 * @property string $hash
 * @property User $User
 * @property Doctrine_Collection $Emails
 * @property MailingList2Email $MailingList2Email
 * 
 * @method integer             getUserId()            Returns the current record's "user_id" value
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getHash()              Returns the current record's "hash" value
 * @method User                getUser()              Returns the current record's "User" value
 * @method Doctrine_Collection getEmails()            Returns the current record's "Emails" collection
 * @method MailingList2Email   getMailingList2Email() Returns the current record's "MailingList2Email" value
 * @method MailingList         setUserId()            Sets the current record's "user_id" value
 * @method MailingList         setName()              Sets the current record's "name" value
 * @method MailingList         setHash()              Sets the current record's "hash" value
 * @method MailingList         setUser()              Sets the current record's "User" value
 * @method MailingList         setEmails()            Sets the current record's "Emails" collection
 * @method MailingList         setMailingList2Email() Sets the current record's "MailingList2Email" value
 * 
 * @package    SystemCore
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMailingList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mailing_list');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('hash', 'string', 8, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => true,
             'length' => 8,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('MailingList2Email as Emails', array(
             'local' => 'id',
             'foreign' => 'mainling_list_id'));

        $this->hasOne('MailingList2Email', array(
             'local' => 'id',
             'foreign' => 'mailing_list_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}