<?php

/**
 * BaseUserData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $point
 * @property text $verify
 * @property User $User
 * 
 * @method integer  getUserId()  Returns the current record's "user_id" value
 * @method integer  getPoint()   Returns the current record's "point" value
 * @method text     getVerify()  Returns the current record's "verify" value
 * @method User     getUser()    Returns the current record's "User" value
 * @method UserData setUserId()  Sets the current record's "user_id" value
 * @method UserData setPoint()   Sets the current record's "point" value
 * @method UserData setVerify()  Sets the current record's "verify" value
 * @method UserData setUser()    Sets the current record's "User" value
 * 
 * @package    SystemCore
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserData extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_data');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('point', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 500,
             ));
        $this->hasColumn('verify', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}