<?php

/**
 * BaseUserTestEmail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $email
 * @property User $User
 * 
 * @method integer       getUserId()  Returns the current record's "user_id" value
 * @method string        getEmail()   Returns the current record's "email" value
 * @method User          getUser()    Returns the current record's "User" value
 * @method UserTestEmail setUserId()  Sets the current record's "user_id" value
 * @method UserTestEmail setEmail()   Sets the current record's "email" value
 * @method UserTestEmail setUser()    Sets the current record's "User" value
 * 
 * @package    SystemCore
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserTestEmail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_test_email');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('email', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}