<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/01/23 19:47:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=systemcore',
  'username' => 'root',
  'password' => 'd4de0fm',
  'name' => 'doctrine',
)),);
