<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/05/26 11:27:17

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=systemcore',
  'username' => 'root',
  'password' => 'd4de0fm',
  'name' => 'doctrine',
)),);
