<?php

/**
 * Email
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    SystemCore
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Email extends BaseEmail
{

	public function getEmailDetails($hash)
	{
		$q = Doctrine_Query::create()
			->from('MailingList2Email m2e')
			->leftJoin('m2e.MailingList ml')
			->where('m2e.email_id =?', $this->getPrimaryKey())
			->andWhere('ml.hash =?', $hash);
		return $q->fetchOne();
	}

	public function getPerson()
	{
		if($this->getName())
		{
			return $this->getName();
		}
		else
		{
			return $this->getEmail();
		}
	}



}
