<?php

/**
 * EmailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Email');
    }

    public function getOrAddEmail($email)
    {
    	$tmp = $this->findOneByEmail($email);
    	if($tmp instanceof Email)
    	{
    		return $tmp;
    	}
    	else
    	{
    		$tmp = new Email();
    		$tmp->setEmail(strtolower($email));
    		$tmp->save();
    		return $tmp;
    	}
    }

    public function sendVerifiedLink($email, $hash, $m2e)
    {
        $host = sfConfig::get('app_global_host');
        $md5_1 = md5($email.$hash.'verify_link');
        $md5_2 = md5($email.$hash.'delete_link');
        
        $url_add = '<a href="'.$host.'/verified?hash='.$hash.'&md5='.$md5_1.'&email='.$m2e.'">Kliknij tutaj</a>';

        $url_delete = '<a href="'.$host.'/remove?hash='.$hash.'&md5='.$md5_2.'&email='.$m2e.'">Kliknij tutaj</a>';

        $list = MailingListTable::getInstance()->findOneByHash($hash);
        $user = $list->getUser();
        $content = $user->getUserData()->getVerify();

        $content = str_replace('{verify_link}', $url_add, $content);
        $content = str_replace('{delete_link}', $url_delete, $content);
        
        Tools::sendEmail($email, 'Weryfikacja adresu email', $content);
    }


        

}