<?php

/**
 * MailingList2EmailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailingList2EmailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MailingList2EmailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MailingList2Email');
    }

    public function findOnebyTwoIds($ml_id, $email_id)
    {
    	$q = Doctrine_Query::create()
    		->from('MailingList2Email')
    		->where('mailing_list_id =?', $ml_id)
    		->andWhere('email_id =?' ,$email_id)
    	;
    	return $q->fetchOne();
    }
}