<?php

/**
 * Mailing2MailingListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Mailing2MailingListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Mailing2MailingListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mailing2MailingList');
    }
}