<?php

/**
 * Mailing2Email
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    SystemCore
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Mailing2Email extends BaseMailing2Email
{
	public function getPerson()
	{
		if($this->getName())
		{
			return $this->getName();
		}
		else
		{
			return $this->getEmail()->getEmail();
		}
	}
}
