<?php

/**
 * Mailing2EmailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Mailing2EmailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Mailing2EmailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mailing2Email');
    }
}