<?php

/**
 * PaymentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaymentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PaymentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Payment');
    }

    public function getPrice($points)
    {
    	if($points > 0)
		{
			if($points <= 1000)
			{
				$p = 0.030;
			}
			else if($points <= 5000)
			{
				$p = 0.025;	
			}
			else if($points < 10000)
			{
				$p = 0.020;
			}
			else
			{
				$p = 0.015;
			}			

			$price = ($points * $p);
			$price = round($price, 2);
			$price = $price * 100;

			$price = str_replace('.', '', $price);
			$price = str_replace(',', '', $price);

			return $price;
		}
		else
		{
			return 0;
		}
    }
}