<?php

/**
 * UserTestEmailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTestEmailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTestEmailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserTestEmail');
    }
}