<?php

/**
 * UserDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserData');
    }
}