# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

download_invoice:
  url: /invoice/donwload/:hash
  class:   sfDoctrineRoute
  options: { model: Payment, type: object}
  param:   { module: tools, action: download }

payment_done:
  url: /payment/:hash
  param: { module: tools, action: payment }

debug:
  url: /debug
  param: {module: debug, action: index }

register:
  url: /register
  param: {module: register, action: index }

payment:
  url: /payment
  param: {module: payment, action: index }

user:
  url: /user
  param: {module: user, action: index }

mailing:
  url: /mainling
  param: {module: mailing, action: index }

mailing_delete_email:
  url: /delete/email/:hash
  param: {module: tools, action: deleteEmail }

mailing_open_email:
  url: /open/:hash
  param: {module: tools, action: openEmail }

mailing_runs_email:
  url: /mailingrun/:hash
  param: {module: tools, action: mailingRun }

email:
  url: /email
  param: {module: email, action: index }

mailing_list:
  url: /mainling_list
  param: {module: mailing_list, action: index }

add_subscriber:
  url: /add_subscriber
  param: {module: tools, action: addSubscriber }

verified:
  url: /verified
  param: {module: tools, action: verified }

remove:
  url: /remove
  param: {module: tools, action: remove }

link:
  url: /link/:hash
  param: {module: tools, action: link }

preview: 
  url: /preview/:hash
  param: {module: tools, action: preview }

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
