<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/12/24 13:19:52

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=systemcore',
  'username' => 'root',
  'password' => 'aman12pl',
  'name' => 'doctrine',
)),);
