<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/01/05 15:56:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=systemcore',
  'username' => 'root',
  'password' => 'aman12pl',
  'name' => 'doctrine',
)),);
