<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/12/28 12:27:39

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=systemcore',
  'username' => 'root',
  'password' => 'pawel12pl',
  'name' => 'doctrine',
)),);
