actAs: [Timestampable]
options:
  type: INNODB
  collate: utf8_unicode_ci
  charset: utf8  

User:
  columns:    
    username:         {type: string(255), notnull: true, unique: true}
    api_token:        {type: string(255), notnull: true, unique: true}
    api_secret: 	  {type: string(255), notnull: true, unique: true}
    first_name: 	  {type: string(255), notnull: true}
    last_name:     	  {type: string(255), notnull: true}
    email:    		  {type: string(255), notnull: true, unique: true}
    phone:    		  {type: string(255), notnull: false}
    street:    		  {type: string(255), notnull: false}
    post_code:  	  {type: string(255), notnull: false}
    city:       	  {type: string(255), notnull: false}
    country:          {type: string(255), notnull: false}
    is_company:       {type: boolean, default: 0}
    nip:              {type: string(255), notnull: false}
    status:		  {type: integer, notnull: true, default: 1}
    invoice_id:		  {type: integer, notnull: false}
  relations:
    UserData:
      type: one
      foreignType: one
      local: id
      foreign: user_id
    UserTestEmail:
      type: many
      local: id
      foreign: user_id
    MailingLists:
      class: MailingList
      type: many
      foreignType: one
      local: id
      foreign: user_id      
    Mailings:
      type: many
      foreignType: one
      local: id
      foreign: user_id  
    Payments:
      type: many
      foreignType: one
      local: id
      foreign: user_id

UserData:
  columns:    
    user_id:     {type: integer, notnull: true}
    point:			 {type: integer, notnull: true, default: 500}
    verify:      {type: text, notnull: false }
  relations:
    User:
      type: one
      foreignType: one
      local: user_id
      foreign: id
      onDelete: CASCADE   

UserTestEmail:
  columns:    
    user_id:         {type: integer, notnull: true}
    email:           {type: string,  notnull: true}
  relations:
    User:
      type: one
      local: user_id
      foreign: id
      onDelete: CASCADE       

MailingList:
  columns:    
    user_id:         {type: integer, notnull: true}
    name:			 {type: string(255), notnull: false}
    hash:			 {type: string(8), notnull: false, unique: true}
  relations:
    User:
      type: one
      foreignType: many
      local: user_id
      foreign: id
      onDelete: CASCADE
    Emails:
      class: MailingList2Email
      type: many
      local: id
      foreign: email_id
    Mailings:
      class: Mailing
      refClass: Mailing2MailingList
      type: many
      local: mailing_list_id
      foreign: mailing_id      

Email:
  columns: 
    email: {type: string(255), notnull: true, unique: true}
  relations:
    MailingLists:
      class: MailingList2Email
      type: many
      local: id
      foreign: mailing_list_id
    Mailings:
      class: Mailing
      refClass: Mailing2Email
      type: many
      local: email_id
      foreign: mailing_id      

MailingList2Email:
  columns:    
    mailing_list_id:         {type: integer, notnull: true, primary: true}
    email_id:    			 {type: integer, notnull: true, primary: true}
    name:					 {type: string(255), notnull: true}
    phone:					 {type: string(255), notnull: true}
    status:					 {type: integer, notnull: true, default: 1}
  relations:
    MailingList:
      local: mailing_list_id
      foreign: id
      onDelete: CASCADE
    Email:
      local: email_id
      foreign: id
      onDelete: CASCADE

Mailing:
  columns:
    user_id:  {type: integer, notnull: true}
    title:    {type: string(255), notnull: true}
    html:     {type: text, notnull: false }
    text:     {type: text, notnull: false }
    public:   {type: text, notnull: false }
    settings: {type: text, notnull: false }
    status:   {type: integer, notnull: true, default: 1}
    hash:      {type: string(8), notnull: false, unique: true}
    time_start: {type: timestamp, format: Y-m-d H:i:s, notnull: false }
    time_end:   {type: timestamp, format: Y-m-d H:i:s, notnull: false }
    is_deleted: {type: boolean, default: 0}
  relations:
    User:
      type: one
      local: user_id
      foreign: id  
    MailingLists:
      class: MailingList
      refClass: Mailing2MailingList
      type: many
      local: mailing_id
      foreign: mailing_list_id
    MailingEmails:
      class: Email
      refClass: Mailing2Email
      type: many
      local: mailing_id
      foreign: email_id      

Mailing2Email:
  columns:
    mailing_id:  {type: integer, notnull: true, primary: true}
    email_id:    {type: integer, notnull: true, primary: true}
    status:      {type: integer, notnull: true, default: 1}
  relations:
    Mailing:
      local: mailing_id
      foreign: id
      onDelete: CASCADE
    Email:
      local: email_id
      foreign: id
      onDelete: CASCADE

Mailing2MailingList:
  columns:
    mailing_id:  {type: integer, notnull: true, primary: true}
    mailing_list_id:  {type: integer, notnull: true, primary: true}
  relations:
    MailingList:
      local: mailing_list_id
      foreign: id
      onDelete: CASCADE
    Mailing:
      local: mailing_id
      foreign: id
      onDelete: CASCADE

Payment:
  columns:
    user_id:    {type: integer, notnull: true}
    hash:       {type: string(255), notnull: true, unique: true}
    points:     {type: integer, notnull: true, default: 0}
    price:      {type: integer, notnull: true, default: 0}
    symbol:     {type: string(255), notnull: true, default: 'PLN'}
    status:     {type: integer, notnull: true, default: 1}
    invoice_id: {type: integer, notnull: false}
  relations:
    User:
      type: one
      local: user_id
      foreign: id
      onDelete: CASCADE    

Config:
  columns:    
    record:           {type: string(255), notnull: true, unique: true}
    value:            {type: text, notnull: true }


